import { Link } from 'react-router-dom';
import {
  LegalDocumentShell,
  Section,
  SubSection,
  List,
  Callout,
  Placeholder,
  ContactLink,
} from '../../../components/legal/LegalDocument';
import {
  TERMS_LABEL_EN,
  TERMS_PATH,
  PRIVACY_VERSION,
  LEGAL_UPDATED_AT_EN,
  LEGAL_CONTACT_EMAIL,
} from '../../../config/legal';

// ─── Privacy Policy, versão em inglês ────────────────────────────────────────
//
// Tradução de cortesia da versão em português, publicada em 2026-09-09, sob o
// MESMO número de versão (`PRIVACY_VERSION`). Ver o cabeçalho de
// `TermsOfUseEn.tsx` para a regra completa: a página diz que é tradução e que o
// português prevalece, e mudança no original vem para cá no mesmo commit.
//
// Os pontos que não podem ser "simplificados" numa revisão futura sem ler o
// código de novo são os mesmos do original: a exclusão é anonimização com
// preservação do registro de negócio (seção 13), não existe purga automática
// de dado nenhum (seção 12), nenhum terceiro fora dos listados na seção 8, e o
// navegador do visitante não fala com a CDN do Instagram.
export default function PrivacyPolicyEn() {
  return (
    <LegalDocumentShell
      notice={
        <>
          <p>
            <strong className="text-foreground">
              This is a courtesy translation of the Portuguese original.
            </strong>{' '}
            The Portuguese version of this Privacy Policy is the binding one, and it is the version
            recorded when you accept it. In case of any divergence between the two texts, the
            Portuguese version prevails.
          </p>
          <p>
            Both versions carry the same version number, {PRIVACY_VERSION}, and describe the same
            document. The original is on this same page: switch the language at the top to read it.
          </p>
        </>
      }
      updatedLabel={`Version ${PRIVACY_VERSION} · updated ${LEGAL_UPDATED_AT_EN}`}
      title="Privacy Policy"
      intro={
        <>
          <p>
            This Privacy Policy explains how <strong className="text-foreground">TAYRO</strong>{' '}
            collects, uses, stores and shares personal data, and what rights you have over that
            data, under the Brazilian General Data Protection Law (LGPD, Law No. 13,709/2018).
          </p>
          <p>
            It applies to everyone who uses or visits the platform, including{' '}
            <strong className="text-foreground">creators, brands and visitors</strong> of the public
            pages.
          </p>
          <p>
            This Policy describes how the platform works{' '}
            <strong className="text-foreground">today</strong>. Where a feature does not exist, that
            is stated expressly rather than left out.
          </p>
        </>
      }
      footer={
        <Link
          to={TERMS_PATH}
          className="font-mono text-[10px] uppercase tracking-widest text-kinetic-muted transition-colors hover:text-lime"
        >
          {TERMS_LABEL_EN}
        </Link>
      }
    >
      <Section id="controlador" title="1. Who we are and who the controller is">
        <p>
          TAYRO is a platform that brings brands and creators together so that promotional
          partnerships become possible. The controller of the personal data processed directly by
          the platform is:
        </p>
        <Placeholder>
          <p className="font-medium text-foreground">Pedro Soares de Souza Garcia</p>
          <p>CPF: 119.407.186-43</p>
          <p>Email: {LEGAL_CONTACT_EMAIL}</p>
        </Placeholder>
        <p>
          No data protection officer has been formally appointed yet. Requests relating to personal
          data should be sent to the email address above, which is the channel indicated in this
          Policy for that purpose.
        </p>
        <p>
          Besides TAYRO, a <strong className="text-foreground">brand</strong> that receives creator
          data through the platform starts processing it for its own purposes, such as reviewing
          applications, making contact, managing the campaign and following the partnership. To that
          extent, the brand acts as a controller of the data it receives and is answerable for the
          processing it carries out. Section 9 details what is shared between the parties.
        </p>
      </Section>

      <Section id="dados-coletados" title="2. What data we collect">
        <p>The personal data processed by TAYRO has four origins:</p>
        <List
          items={[
            'data you provide yourself when creating an account, filling in your profile and using the features (sections 3 and 4)',
            'data obtained from external sources, based on the Instagram username the creator provides (section 5)',
            'data generated by the use of the platform itself, such as records of applications, decisions, rewards and results (sections 3 and 4)',
            'technical data relating to the operation and the security of the application (section 6)',
          ]}
        />
        <p>
          <strong className="text-foreground">
            No feature has fields intended to collect
          </strong>{' '}
          date of birth, identity documents, tax or company registration numbers of users, bank
          details, credit card data, payment data, precise geolocation data or biometric data.
        </p>
        <p>
          TAYRO also{' '}
          <strong className="text-foreground">
            does not deliberately request sensitive personal data
          </strong>{' '}
          within the meaning of the LGPD as part of its registration flows or features. Users may,
          however, enter information of that nature in free text fields, such as the profile
          biography, the message in an application, the caption of a piece of content or the notes
          on a reward. In those cases, the processing will comply with applicable law.
        </p>
        <p>
          The platform also{' '}
          <strong className="text-foreground">has no file upload</strong>: no video, photo or
          document is sent to our servers by users.
        </p>
      </Section>

      <Section id="dados-creator" title="3. Creator data">
        <SubSection title="3.1. Registration and profile data">
          <List
            items={[
              'name',
              'email address',
              'phone number',
              'password (stored only as a hash, never in readable text)',
              'Instagram username (@)',
              'city',
              'niches',
              'biography',
              'profile image address, when provided manually',
              'TikTok username, when provided',
            ]}
          />
          <p>
            The TikTok username is an optional profile field. It is currently{' '}
            <strong className="text-foreground">
              not shown to brands or on the public profile
            </strong>
            , and is used only in your own account and in the export of your data.
          </p>
          <p>
            The Instagram username is set at first registration and, in this flow, cannot be edited
            by the creator afterwards.
          </p>
        </SubSection>

        <SubSection title="3.2. Data generated by use of the platform">
          <List
            items={[
              'applications submitted, with date, campaign, state (pending, approved, rejected or withdrawn) and date of the decision',
              'the message written by the creator when applying, when filled in',
              'addresses (links) of the content recorded, media type, optional caption, review state and the comment written by the brand',
              'rewards recorded by the brand in their name, with type, value, state, notes and date',
              'partnership results reported by the brand, with reach, impressions, coupons used and notes, when filled in',
              'the choice of keeping the public profile active or not, and the choice of hiding specific results',
            ]}
          />
        </SubSection>

        <SubSection title="3.3. Record of acceptance of the documents">
          <p>
            When an account is created, the platform records, associated with your account, the
            following data about the acceptance:
          </p>
          <List
            items={[
              'the version of the Terms of Use accepted',
              'the version of this Privacy Policy accepted',
              'the date and time of the acceptance',
              'the date and time of the declaration of being 18 years old or older',
            ]}
          />
          <p>
            The recorded version is set by the server at the moment of acceptance, and is not
            supplied by the browser. Accounts created before September 4, 2026, when this record
            came into existence, do not have this data filled in.
          </p>
        </SubSection>
      </Section>

      <Section id="dados-marca" title="4. Brand data">
        <SubSection title="4.1. Registration and profile data">
          <List
            items={[
              'email address',
              'password (stored only as a hash, never in readable text)',
              'brand name',
              'niches',
              'website',
              'logo image address, when provided',
              'biography or description of the brand',
            ]}
          />
          <p>
            Brand registration does not ask for a company registration number, legal name, address
            or details of a legal representative, and TAYRO does not verify the existence or the
            identity of the registered brand.
          </p>
        </SubSection>

        <SubSection title="4.2. Data generated by use of the platform">
          <List
            items={[
              'campaigns created, with title, description, brief, niches, deadlines, number of spots and state',
              'terms of the offer presented to creators, including amount, type, deadline, description and commission percentage',
              'decisions taken on each application received, with date',
              'content reviews, with the state assigned and the comment written',
              'rewards recorded, with type, value, state, notes and dates',
              'partnership results reported, and the authorisation, or not, for them to appear on the public profile of the creator',
            ]}
          />
        </SubSection>

        <SubSection title="4.3. Record of acceptance of the documents">
          <p>
            Brand registration records the same acceptance data described in item 3.3, under the
            same conditions.
          </p>
        </SubSection>
      </Section>

      <Section id="fontes-externas" title="5. Data obtained from external sources">
        <Callout>
          <p>
            TAYRO <strong className="text-foreground">has no official integration</strong> with
            Instagram or with Meta, and is not a partner of or authorised by them.
          </p>
          <p>
            Profile information is obtained through an{' '}
            <strong className="text-foreground">unofficial external provider</strong>, accessed via
            RapidAPI, based on information publicly available on the profile whose username the
            creator provided. It is{' '}
            <strong className="text-foreground">not official Instagram data</strong> and is not
            audited by us.
          </p>
        </Callout>
        <p>Depending on availability in the source consulted, we may obtain and store:</p>
        <List
          items={[
            'the username and the profile identifier on the source platform',
            'the follower count',
            'the address of the profile picture',
            'recent posts, with the address of the post, the address of the preview image, the number of likes and the number of comments',
          ]}
        />
        <p>From that information, the platform also generates and stores:</p>
        <List
          items={[
            <>
              an <strong className="text-foreground">engagement rate estimate</strong>, calculated
              by us as the average of likes and comments per recent post consulted, divided by the
              follower count. Instagram does not publish this metric: the number is an estimate by
              TAYRO, and not an official metric.
            </>,
            'the date and time of the last query, and whether it succeeded, is in progress or failed',
            <>
              <strong className="text-foreground">copies of the images themselves</strong>, meaning
              the profile picture and the post previews, stored by us.
            </>,
          ]}
        />
        <p>
          The image copies exist for a technical reason: the addresses provided by the Instagram
          content delivery network are temporary and expire, so keeping only the address would make
          the images disappear from the screen after some time. The images are fetched{' '}
          <strong className="text-foreground">by our servers</strong> and served again from our own
          domain: the browser of someone viewing a TAYRO page does not connect to the Instagram
          content delivery network.
        </p>
        <p>
          When a username is provided in the registration and application forms, the platform
          queries the external source only to indicate whether that username appears to exist. That
          check does not confirm ownership and does not return profile data.
        </p>
        <p>
          The query is made when the creator provides the username, when they submit an application
          and when an update is requested manually on the platform, subject to minimum intervals
          between queries.
        </p>
      </Section>

      <Section id="dados-tecnicos" title="6. Technical data and error records">
        <p>
          To keep the platform running, investigate failures and protect the service, technical
          records are generated, which may contain:
        </p>
        <List
          items={[
            'information about errors that occurred in the application, including the error message, the section of code where it occurred, the address of the page or route accessed and information about the browser or the environment',
            'internal identifiers of platform records, such as the identifier of a creator profile, where needed to diagnose the failure',
            'operational records of the application running, such as failures in sending emails and the volume of access to certain listings',
          ]}
        />
        <p>
          The error monitoring tool used is configured{' '}
          <strong className="text-foreground">
            not to collect personal data of the user automatically
          </strong>
          , including the IP address, and to strip, before sending, the content submitted on
          authentication routes and the authentication and session headers. Passwords and
          credentials are therefore not sent to that tool.
        </p>
        <p>
          The platform <strong className="text-foreground">does not use session replay</strong>,
          does not record the screen, the clicks or the typing of the user, and does not use
          analytics, behavioural profiling or advertising tools.
        </p>
        <p>
          When sending an email fails, the destination address is recorded in partially masked form
          in the error record, preserving only what is needed for diagnosis.
        </p>
        <p>
          The hosting providers may, on their own account and in order to operate their
          infrastructure, keep access logs, including IP addresses, under their respective policies.
        </p>
      </Section>

      <Section id="finalidades" title="7. What we use the data for, and on what legal basis">
        <p>We use personal data to:</p>
        <List
          items={[
            'create, maintain and administer accounts, and authenticate users',
            'allow brands to create, publish and manage campaigns',
            'allow creators to find campaigns and submit applications',
            'show brands the information needed to review applications and decide on them',
            'record content, rewards and partnership results, and show them to the counterparty',
            'create and maintain the profile and the media kit of the creator, and make them public when they choose so',
            'send the communications needed for the account to work, such as setting and recovering a password, decisions on applications, recording of results, change of email address and confirmation of account deletion',
            'identify, investigate and fix technical failures',
            'protect the platform and its users against fraud, abuse and unauthorised access',
            'record the acceptance of the legal documents and the declaration of legal age',
            'comply with legal obligations and exercise rights regularly',
          ]}
        />
        <p>
          Each processing activity is carried out on the{' '}
          <strong className="text-foreground">legal basis applicable to its purpose</strong>. The
          bases used by TAYRO, as the case may be, are the following:
        </p>
        <List
          items={[
            <>
              <strong className="text-foreground">
                Performance of a contract and of preliminary procedures
              </strong>{' '}
              (art. 7, V): creating and maintaining accounts, authentication, the working of
              campaigns, applications, content records, rewards and results, and sending the
              communications needed for those features.
            </>,
            <>
              <strong className="text-foreground">Legitimate interests</strong> (art. 7, IX):
              security of the platform, prevention of fraud and abuse, diagnosis and correction of
              technical failures, and keeping the record of acceptance of the documents. This basis
              is assessed for each specific purpose, considering the necessity of the processing and
              the legitimate expectations of the data subject, and{' '}
              <strong className="text-foreground">
                does not generically authorise any processing
              </strong>
              .
            </>,
            <>
              <strong className="text-foreground">Consent</strong> (art. 7, I): where processing
              depends on consent, it is requested specifically and separately from the acceptance of
              the documents. That is the case of the activation of the public profile by the
              creator, which is optional, starts switched off and{' '}
              <strong className="text-foreground">can be withdrawn at any time</strong>, and of the
              publication of partnership results on that profile, which also depends on the
              authorisation of the brand. Withdrawal does not affect the lawfulness of processing
              carried out while the consent was in force.
            </>,
            <>
              <strong className="text-foreground">
                Compliance with a legal or regulatory obligation
              </strong>{' '}
              (art. 7, II) and{' '}
              <strong className="text-foreground">regular exercise of rights</strong> (art. 7, VI):
              retention of records in the situations in section 12 and compliance with decisions of
              a competent authority.
            </>,
          ]}
        />
        <Callout>
          <p>
            Accepting this Policy at registration means{' '}
            <strong className="text-foreground">
              being aware of and accepting this document
            </strong>
            .
          </p>
          <p>
            It is not a generic consent to any and all processing: each processing activity relies
            on the legal basis that corresponds to it, as listed above. Where consent is the basis,
            it is requested separately and specifically, as in the case of the public profile.
          </p>
        </Callout>
        <p>
          The list above describes, in general terms, the legal bases applicable to the purposes
          described in this Policy. It does not claim to exhaust the analysis of each operation
          individually: where a new purpose comes into existence, the corresponding legal basis will
          be identified and this Policy will be updated.
        </p>
        <p>
          TAYRO <strong className="text-foreground">does not sell personal data</strong>, does not
          rent contact lists, does not use data for behavioural advertising and does not make
          automated decisions producing legal effects on data subjects. The decision on an
          application is taken by a person, at the brand.
        </p>
      </Section>

      <Section id="compartilhamento" title="8. Who we share data with">
        <p>
          We use service providers to operate the platform. Each one receives only the data needed
          for its function:
        </p>
        <List
          items={[
            <>
              <strong className="text-foreground">Neon</strong> (database). Stores practically all
              the data described in sections 3, 4 and 5, including registration data, profiles,
              campaigns, applications, content, rewards, results and the Instagram image copies.
            </>,
            <>
              <strong className="text-foreground">Railway</strong> (API hosting). Runs the server
              application, and therefore processes all data in transit in the features, as well as
              keeping operational records of execution.
            </>,
            <>
              <strong className="text-foreground">Vercel</strong> (web application hosting).
              Delivers the pages to the browser and forwards requests to the API. Receives
              connection data, such as IP address and browser information.
            </>,
            <>
              <strong className="text-foreground">Resend</strong> (email delivery). Receives the
              email address of the recipient and the content of the transactional messages, which
              may contain the name of the creator, the name of the brand, the title of the campaign
              and links for setting or recovering a password.
            </>,
            <>
              <strong className="text-foreground">Sentry</strong> (error monitoring). Receives the
              technical data described in section 6, with no automatic collection of IP address and
              with content and authentication headers stripped. The instance used is configured in
              the European Union region.
            </>,
            <>
              <strong className="text-foreground">
                RapidAPI and the Instagram query provider
              </strong>
              . Receive the Instagram username provided by the creator, in order to query public
              profile information and to check whether that username exists.
            </>,
            <>
              <strong className="text-foreground">Instagram content delivery network</strong>. Our
              servers request from it the profile pictures and the post preview images, using the
              addresses obtained in the query. That request is made by our server, and not by the
              browser of whoever is viewing the page.
            </>,
            <>
              <strong className="text-foreground">GitHub and GitHub Actions</strong> (repository and
              release automation). Used to check, build and publish new versions of the application,
              including applying changes to the structure of the database. Credentials for the
              production infrastructure are used in that process. The service does not receive
              copies of the personal data of users for its own purposes.
            </>,
          ]}
        />
        <p>
          The platform <strong className="text-foreground">does not currently use</strong> a payment
          provider, a file storage service, an analytics tool, an advertising network, a marketing
          automation platform or a customer support tool with access to the data.
        </p>
        <p>
          Personal data may also be shared with public authorities where there is a legal
          obligation, a court order or a decision of a competent authority, and with advisers for
          the regular exercise of rights.
        </p>
      </Section>

      <Section id="entre-usuarios" title="9. Sharing between creators and brands">
        <p>
          The purpose of the platform is to bring the two sides together, and for that reason
          certain information is shown from one side to the other. The sharing is limited to what is
          necessary for the feature used.
        </p>

        <SubSection title="9.1. What the brand sees about the creator">
          <p>
            When a creator applies to a campaign, the brand responsible starts seeing, about them:
          </p>
          <List
            items={[
              'name',
              'phone number',
              'Instagram username, with a link to the profile on the social network',
              'city and niches',
              'profile picture and preview images of the recent posts',
              'follower count and the engagement estimate calculated by TAYRO',
              'the message written in the application, when filled in',
              'the content they recorded in that partnership, with link, type, caption and state',
              'the state of the application and the related dates',
            ]}
          />
          <p>
            The brand can also see, on a single screen, all the creators whose applications it has
            approved in any of its campaigns, with the same information above. The phone number is
            shown in a way that allows direct contact, including through a messaging app.
          </p>
        </SubSection>

        <SubSection title="9.2. What the creator sees about the brand">
          <List
            items={[
              'brand name, logo and website',
              'campaign information, including title, description, brief, niches, deadlines and number of spots',
              'the terms of the offer presented',
              'the decision on their application',
              'the comment written by the brand when reviewing content',
              'the rewards recorded in their name, with type, value, state and notes',
              'the partnership results reported by the brand, with an indication of who reported them',
            ]}
          />
        </SubSection>

        <SubSection title="9.3. The email address of the parties">
          <Callout>
            <p>
              The <strong className="text-foreground">email address</strong> of creators and brands
              is <strong className="text-foreground">not made available to the counterparty</strong>{' '}
              by the current features of the platform. It is used by TAYRO for authentication and
              for sending the communications of the account.
            </p>
          </Callout>
          <p>
            The email address may, of course, reach the counterparty if the user provides it in a
            free text field, such as the message of an application, or outside the platform.
          </p>
        </SubSection>
      </Section>

      <Section id="perfil-publico" title="10. Public creator profile">
        <p>
          The public profile <strong className="text-foreground">starts switched off</strong>. It
          only comes into existence when the creator switches it on, and that activation is the
          consent for publishing the information below.
        </p>
        <p>
          Once switched on, the profile becomes accessible at a public address, with no login, in
          the format{' '}
          <code className="rounded bg-kinetic-dark px-1 py-0.5 text-xs">tayro.app.br/c/your-@</code>
          , and starts showing, as far as it has been filled in:
        </p>
        <List
          items={[
            'name and Instagram username',
            'profile picture and preview images of the recent posts',
            'biography, city and niches',
            'phone number',
            'follower count and the engagement estimate calculated by TAYRO',
            'the number of completed partnerships, calculated by the rule stated on the page itself',
            'partnership results, only under the conditions described below',
          ]}
        />
        <p>
          The <strong className="text-foreground">phone number is published together</strong> with
          the rest of the information while the public profile is on. There is no separate option to
          publish the profile without the phone number.
        </p>
        <p>
          The <strong className="text-foreground">email address is never shown</strong> on the
          public profile, and neither is the TikTok username.
        </p>
        <p>
          A partnership result only appears publicly when the brand that reported it has authorised
          the public display, an authorisation that starts switched off, and the creator has not
          hidden that result. The creator can hide each result individually, without switching the
          whole profile off, and can always see, in their account, the results reported by brands,
          whether public or not.
        </p>
        <p>
          As it is an open page, the public profile may be indexed by search engines and copied by
          third parties. Switching it off stops publication from that moment on, but does not reach
          copies, screenshots or indexing already made by third parties, over which TAYRO has no
          control.
        </p>
      </Section>

      <Section id="cookies" title="11. Cookies and browser storage">
        <p>
          TAYRO <strong className="text-foreground">does not use advertising cookies</strong>, third
          party cookies for cross-site tracking, tracking pixels or analytics tools. That is why the
          platform shows no cookie consent banner.
        </p>
        <p>Only the following resources are used, all of them necessary for the service to work:</p>
        <List
          items={[
            <>
              <strong className="text-foreground">Session cookie</strong>. A single first party
              cookie, used to keep you authenticated and to renew the session. It is configured not
              to be accessible by page scripts (HttpOnly), is transmitted only over a secure
              connection in production and has a limited lifetime. It is also what allows us to
              check, when a profile image is loaded, whether you are authorised to see it.
            </>,
            <>
              <strong className="text-foreground">Browser memory during the session</strong>. The
              data used to authorise your actions stays only in the memory of the open tab, and is
              not written to persistent storage on the device.
            </>,
            <>
              <strong className="text-foreground">Local browser storage</strong>, where used, for
              interface preferences of the device itself. That data stays in your browser and is not
              sent to TAYRO.
            </>,
            <>
              <strong className="text-foreground">Application cache</strong>. The platform can be
              installed as an app and caches the interface files so that it works better. The
              responses of the data routes are explicitly excluded from that cache, so that
              information from one account is not left on the device for the next user.
            </>,
          ]}
        />
        <p>
          The typefaces used by the platform are{' '}
          <strong className="text-foreground">served from the TAYRO domain itself</strong>, and not
          by third party servers. Loading a page establishes no connection with any external font
          supplier.
        </p>
      </Section>

      <Section id="retencao" title="12. How long we keep the data">
        <p>
          We keep personal data while the account exists and while it is needed for the purposes of
          this Policy, or while there is another legal basis justifying its retention.
        </p>
        <Callout>
          <p>
            To be exact: the platform{' '}
            <strong className="text-foreground">
              currently has no mechanism for expiring or automatically deleting any data
            </strong>{' '}
            after a set period.
          </p>
          <p>
            That is why this Policy does not set fixed retention periods that could not be met. Data
            is deleted or anonymised when you request the deletion of the account, as set out in
            section 13, or when it is no longer necessary and that deletion is carried out by us.
          </p>
        </Callout>
        <p>After a deletion request, certain data may be retained where it is needed for:</p>
        <List
          items={[
            'compliance with a legal or regulatory obligation',
            'the regular exercise of rights, including in judicial, administrative or arbitration proceedings',
            'fraud prevention and the security of the data subject and of third parties',
            'preserving the history of the commercial relationship between brand and creator, including evidence of the work carried out and of the consideration recorded',
            'other situations authorised by the LGPD',
          ]}
        />
        <p>
          The service providers listed in section 8 may keep technical copies and records of their
          own for periods set out in their respective policies, including infrastructure backups.
        </p>
      </Section>

      <Section id="exclusao" title="13. Deletion and anonymisation of the account">
        <p>
          This section describes exactly what happens today when a creator requests the deletion of
          their account through the feature available in the Profile, which requires confirming the
          password.
        </p>
        <Callout>
          <p>
            Deletion{' '}
            <strong className="text-foreground">
              is not the complete removal of every record
            </strong>
            . It removes and anonymises the data that identifies you, and preserves the records of
            the commercial relationship, with no link to your identity.
          </p>
        </Callout>
        <SubSection title="13.1. What is removed or anonymised">
          <List
            items={[
              'name, biography, phone number, city, niches, Instagram username, TikTok username and the profile image address provided manually',
              'the copies of profile and post images we kept, which are deleted',
              'the follower count, the engagement estimate and the recent posts stored',
              'the email address, replaced by a value with no correspondence to the original address',
              'the password, whose record is replaced by a random, discarded value, so that the previous password ceases to exist on the platform',
              'the session records and every pending link for setting or recovering a password, which are invalidated',
              'the activation of the public profile, which is switched off, ending public display',
            ]}
          />
          <p>
            Applications still pending a decision move to the withdrawn state. The account stops
            allowing access.
          </p>
        </SubSection>
        <SubSection title="13.2. What remains stored">
          <p>
            The records below are preserved, without the identifying data removed in the previous
            item, because they document the commercial relationship and the work carried out, and
            the brand involved may also need them for the regular exercise of rights and to comply
            with its own obligations:
          </p>
          <List
            items={[
              'the applications submitted, with campaign, state and dates',
              'the content recorded, with the address (link) provided, the type, the caption and the review state',
              'the rewards recorded by the brand, with type, value, state, notes and dates',
              'the partnership results reported by the brand',
              'the record of acceptance of the documents, that is, the versions accepted and the dates of acceptance and of the declaration of legal age, which are preserved as evidence that the relationship existed under a given version of the documents and do not identify the person',
            ]}
          />
          <p>
            It is important to note that those records may contain{' '}
            <strong className="text-foreground">free text fields</strong>, written by you or by the
            brand, such as the message sent in an application, the caption of a piece of content,
            the address of the content and the notes on a reward or a result. Where there is
            personal information in those texts, it stays stored in those records after the account
            is deleted.
          </p>
          <p>
            If you want those texts deleted or anonymised as well, you can request it through the
            contact channel in this Policy, and the request will be assessed considering the
            retention situations in section 12.
          </p>
        </SubSection>
        <SubSection title="13.3. Brand accounts">
          <p>
            The platform <strong className="text-foreground">does not yet have</strong> a deletion
            feature for brand accounts. The request must be made through the contact channel in this
            Policy and will be processed by us.
          </p>
        </SubSection>
        <p>
          Once the deletion is completed, we send a communication to the original email address,
          stating what was removed and what remains.
        </p>
      </Section>

      <Section id="direitos" title="14. Your rights">
        <p>
          The LGPD gives you, as a data subject, the rights to confirmation that processing exists,
          access to the data, correction of incomplete, inaccurate or outdated data, anonymisation,
          blocking or deletion of unnecessary data or data processed in breach of the law,
          portability, information about sharing, information about the possibility of not giving
          consent, withdrawal of consent and review of automated decisions.
        </p>

        <SubSection title="14.1. What you can do on the platform itself">
          <List
            items={[
              <>
                <strong className="text-foreground">Export my data.</strong> Available in the
                Account section of your Profile, for creators and for brands. It generates a file
                with the data associated with your account, including profile, applications,
                content, rewards, results and the acceptance record. The file does not include the
                password, session credentials or the stored image copies.
              </>,
              <>
                <strong className="text-foreground">Correct your data.</strong> By editing the
                fields available in your Profile.
              </>,
              <>
                <strong className="text-foreground">Change email address and password.</strong> In
                the Account section of your Profile.
              </>,
              <>
                <strong className="text-foreground">
                  Withdraw the consent for the public profile.
                </strong>{' '}
                By switching the public profile off in your Profile, or by hiding results
                individually.
              </>,
              <>
                <strong className="text-foreground">Delete the account.</strong> Available in the
                Profile, for creators, with the effects described in section 13.
              </>,
            ]}
          />
          <p>
            The export available on the platform covers the data associated with your account, and
            not necessarily each and every piece of data processed in any context. Portability to
            another supplier, where applicable, will follow the rules of the Brazilian data
            protection authority (ANPD) and must be requested through the channel below.
          </p>
        </SubSection>

        <SubSection title="14.2. What has to be requested by email">
          <List
            items={[
              'deletion of a brand account, while no equivalent feature exists',
              'deletion or anonymisation of the free text fields described in item 13.2',
              'detailed information about the entities your data has been shared with',
              'portability of the data to another supplier, under the applicable rules',
              'anonymisation or blocking of specific data',
              'information about and review of automated processing, where applicable',
              'any other request that cannot be met through the features above',
            ]}
          />
          <ContactLink />
          <p>
            Requests will be assessed and answered within the deadlines and conditions of applicable
            law. We may need additional information to confirm your identity before meeting a
            request, as a security measure.
          </p>
          <p>
            You may also file a complaint with the Brazilian data protection authority (ANPD).
          </p>
        </SubSection>
      </Section>

      <Section id="seguranca" title="15. Security">
        <p>
          We take technical and organisational measures to protect personal data against
          unauthorised access, loss, alteration, destruction and other forms of inappropriate
          processing. Among them:
        </p>
        <List
          items={[
            'passwords stored only as a hash, using an algorithm designed for that purpose (bcrypt), and never in readable text',
            'communication between browser and application over an encrypted connection (HTTPS)',
            'authentication by a short lived token, kept only in the memory of the browser, renewed through a session cookie that page scripts cannot access',
            'renewal of session credentials on each use, so that the previous credential stops being valid',
            'termination of the other sessions when the password is changed',
            'authorisation controls applied to the routes of the application, including checking who may view each profile image',
            'rate limiting, with stricter limits on the authentication and credential routes',
            'size limits and format validation on the fields submitted to the application',
            'restriction of the error messages shown to the user, so as not to reveal internal details of the application',
            'error monitoring configured not to collect personal data by default and to strip content and authentication headers',
            'access control over the infrastructure and the services used by the platform',
          ]}
        />
        <p>
          No system is completely secure, and we cannot guarantee absolute security. If you identify
          or suspect a security incident relating to your account, get in touch through the channel
          in this Policy. If a security incident with relevant risk or harm occurs, we will take the
          measures required by the LGPD, including notifying the ANPD and the affected data subjects
          where applicable.
        </p>
      </Section>

      <Section id="transferencia" title="16. International transfer of data">
        <p>
          Some of the service providers listed in section 8 are foreign companies or use
          infrastructure located outside Brazil. The processing of personal data may therefore
          involve international transfer.
        </p>
        <p>
          Among the services used, we have confirmed that the error monitoring instance (Sentry) is
          configured in the <strong className="text-foreground">European Union</strong>. For the
          other services, the exact location of the infrastructure may vary according to the
          configuration and the region adopted by each supplier, and for that reason we do not state
          here a specific country that we cannot confirm.
        </p>
        <p>
          Where there is international transfer, TAYRO will adopt the mechanisms and safeguards
          provided for in the LGPD and in the rules of the ANPD, seeking to ensure an adequate level
          of protection, with transparency as to the purpose, the destination, the sharing, the
          responsibilities and the applicable security measures.
        </p>
      </Section>

      <Section id="menores" title="17. Minors">
        <p>
          TAYRO is intended exclusively for people who are{' '}
          <strong className="text-foreground">18 years old or older</strong> and does not seek to
          collect personal data of minors.
        </p>
        <p>
          When creating an account, it is mandatory to declare being 18 years old or older, and that
          declaration is recorded with date and time. The platform{' '}
          <strong className="text-foreground">
            does not ask for a date of birth and performs no documentary, biometric or automated age
            verification
          </strong>
          : what exists is the declaration made by the user.
        </p>
        <p>
          On becoming aware that an account belongs to a person under 18, we may close it and delete
          or anonymise the personal data, subject to the legal situations of retention. In that
          case, the legal guardian may get in touch through the channel in this Policy.
        </p>
      </Section>

      <Section id="alteracoes" title="18. Changes to this Policy">
        <p>
          This Policy may be updated because of changes in the features of the platform, in the
          services used or in applicable law.
        </p>
        <p>
          Each version is identified by a version number and a date, stated at the top of this page.
          The version in force is the one published here.
        </p>
        <p>
          Where a change is relevant to your rights or to the way your data is processed, we will
          seek to communicate it by email, by a notice on the platform or by another appropriate
          means, and we may request a new acceptance.
        </p>
      </Section>

      <Section id="contato" title="19. Contact">
        <p>
          For questions, requests or complaints relating to the processing of personal data by
          TAYRO, and to exercise the rights described in section 14, get in touch:
        </p>
        <ContactLink />
        <p>
          The identification of the controller is in section 1. The rules for using the platform are
          in the{' '}
          <Link
            to={TERMS_PATH}
            className="text-lime underline underline-offset-2 hover:text-foreground"
          >
            {TERMS_LABEL_EN}
          </Link>
          .
        </p>
      </Section>
    </LegalDocumentShell>
  );
}
